name: "Readarr"
description: "Ebook and audiobook collection manager for Usenet and BitTorrent users"
version: "1.0.3"
slug: "readarr"
init: false
arch:
  - aarch64
  - amd64
ports:
  8787/tcp: 8787
ports_description:
  8787/tcp: "Readarr Web Interface"
map:
  - addon_config:rw
  - media:rw
  - share:rw
ingress: true
ingress_port: 8787
panel_icon: mdi:book-open-page-variant
panel_title: "Readarr"
startup: services
boot: auto
options:
  PUID: 0
  PGID: 0
schema:
  PUID: "int?"
  PGID: "int?"
